// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM2-P0qucZCsYtakgzhueM6s8z4YLpX68',
    appId: '1:1011184674042:web:f9bb6621aa75088b4ad543',
    messagingSenderId: '1011184674042',
    projectId: 'flutter-multi-store-app-69e57',
    authDomain: 'flutter-multi-store-app-69e57.firebaseapp.com',
    storageBucket: 'flutter-multi-store-app-69e57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaQkUFGSt8jyzRuifCl6ea21x7uG7tP5E',
    appId: '1:1011184674042:android:4c2f801ced7b59b24ad543',
    messagingSenderId: '1011184674042',
    projectId: 'flutter-multi-store-app-69e57',
    storageBucket: 'flutter-multi-store-app-69e57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nAAEzIdY16UvosNmllgrU3VlmsMsbi0',
    appId: '1:1011184674042:ios:eeb137b07a1a61314ad543',
    messagingSenderId: '1011184674042',
    projectId: 'flutter-multi-store-app-69e57',
    storageBucket: 'flutter-multi-store-app-69e57.appspot.com',
    iosClientId: '1011184674042-054c25g1vr9lec7ml5jasortmeqo3gof.apps.googleusercontent.com',
    iosBundleId: 'com.multi.web.admin.flutterMultiWebAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1nAAEzIdY16UvosNmllgrU3VlmsMsbi0',
    appId: '1:1011184674042:ios:eeb137b07a1a61314ad543',
    messagingSenderId: '1011184674042',
    projectId: 'flutter-multi-store-app-69e57',
    storageBucket: 'flutter-multi-store-app-69e57.appspot.com',
    iosClientId: '1011184674042-054c25g1vr9lec7ml5jasortmeqo3gof.apps.googleusercontent.com',
    iosBundleId: 'com.multi.web.admin.flutterMultiWebAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM2-P0qucZCsYtakgzhueM6s8z4YLpX68',
    appId: '1:1011184674042:web:72dd4e5ef5d30b6b4ad543',
    messagingSenderId: '1011184674042',
    projectId: 'flutter-multi-store-app-69e57',
    authDomain: 'flutter-multi-store-app-69e57.firebaseapp.com',
    storageBucket: 'flutter-multi-store-app-69e57.appspot.com',
  );
}
